import { Router, type IRouter } from "express";
import healthRouter from "./health";
import connectRouter from "./connect";
import connectorsRouter from "./connectors";
import telegramWebhookRouter from "./telegramWebhook";
import instagramRouter from "./instagram";
import vkRouter from "./vk";
import storeRouter from "./store";
import publishRouter from "./publish";
import enrichRouter from "./enrich";
import productsRouter from "./products";
import productResearchRouter from "./productResearch";
import youtubeRouter from "./youtube";
import telegramMtprotoRouter from "./telegramMtproto";
import statsDashboardRouter from "./statsDashboard";
import ordersRouter from "./orders";
import onehelpRouter from "./onehelp";
import externalAgentRouter from "./externalAgent";

const router: IRouter = Router();

router.use(healthRouter);
router.use(connectRouter);
router.use(connectorsRouter);
router.use(telegramWebhookRouter);
router.use(instagramRouter);
router.use(vkRouter);
router.use(storeRouter);
router.use(publishRouter);
router.use(enrichRouter);
router.use(productsRouter);
router.use(productResearchRouter);
router.use(youtubeRouter);
router.use(telegramMtprotoRouter);
router.use(statsDashboardRouter);
router.use(ordersRouter);
router.use(onehelpRouter);
router.use(externalAgentRouter);

export default router;
